// TOML emitter — renders the leaf policy as structured text with comments.
//
// This is NOT serde serialisation: we generate the TOML by hand so we can
// include section headers, reason fields, comments explaining what the probe
// found, and TODO markers for things the operator must fill in. The output
// should be a readable, reviewable policy document.

use std::path::PathBuf;

use crate::probe::ProbeResult;
use crate::questionnaire::Answers;

/// Render the leaf policy TOML.
pub fn render(
    probe: &ProbeResult,
    answers: &Answers,
    _template_dirs: &[PathBuf],
    _trust_dirs: &[PathBuf],
) -> String {
    let mut out = String::with_capacity(2048);

    // Header comment.
    let kind = if probe.is_script {
        probe.interpreter_name.as_deref().unwrap_or("script")
    } else {
        "binary"
    };
    push_comment(&mut out, &format!(
        "Generated by kennel-compose from {} ({kind})", probe.workload
    ));
    push_comment(&mut out, "Review and tighten before use.");
    out.push('\n');

    // Identity.
    push_kv(&mut out, "template_base", &answers.template_base);
    push_kv(&mut out, "name", &answers.name);
    out.push('\n');

    // Include fragments.
    if !answers.include.is_empty() {
        out.push_str("include = [");
        for (i, frag) in answers.include.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push('"');
            out.push_str(frag);
            out.push('"');
        }
        out.push_str("]\n\n");
    }

    // Exec section.
    push_section_comment(&mut out, "Execution");
    out.push_str("[exec]\n");
    out.push_str("allow = [\n");
    for entry in &probe.exec_allow {
        out.push_str(&format!("    \"{entry}\",\n"));
    }
    out.push_str("]\n");

    // Extra exec.path.
    if !probe.extra_exec_path.is_empty() {
        let mut path_list: Vec<&str> = BASE_EXEC_PATH.to_vec();
        for p in &probe.extra_exec_path {
            path_list.push(p);
        }
        out.push_str("path = [");
        for (i, p) in path_list.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push('"');
            out.push_str(p);
            out.push('"');
        }
        out.push_str("]\n");
    }
    out.push('\n');

    // Extra fs.read grants.
    if !probe.extra_fs_read.is_empty() {
        push_section_comment(&mut out, "Filesystem — non-standard paths from the probe");
        for grant in &probe.extra_fs_read {
            out.push_str("[[fs.read.add]]\n");
            push_kv(&mut out, "path", &grant.path);
            push_kv(&mut out, "reason", &grant.reason);
            out.push('\n');
        }
    }

    // Home write paths.
    if !answers.home_write.is_empty() {
        push_section_comment(&mut out, "Filesystem — home directory access");
        for path in &answers.home_write {
            out.push_str("[[fs.write.add]]\n");
            push_kv(&mut out, "path", path);
            push_kv(&mut out, "reason", "operator-specified write access (read implied)");
            out.push('\n');
        }
    }

    // Network.
    if !answers.net_allow.is_empty() {
        push_section_comment(&mut out, "Network — allowed destinations");
        for entry in &answers.net_allow {
            out.push_str("[[net.proxy.allow.add]]\n");
            push_kv(&mut out, "name", &entry.name);
            out.push_str(&format!("ports = {:?}\n", entry.ports));
            out.push_str("protocol = \"tcp\"\n");
            out.push_str("tls.required = true\n");
            push_kv(&mut out, "reason", &entry.reason);
            out.push('\n');
        }
    }

    // SSH.
    if answers.ssh {
        push_section_comment(&mut out, "SSH egress");
        out.push_str("[ssh]\n");
        out.push_str("allow = true\n");
        out.push_str("# reason = \"operator-specified SSH egress\"\n");
        out.push('\n');
    }

    // Lifecycle.
    push_section_comment(&mut out, "Lifecycle");
    out.push_str("[lifecycle]\n");
    push_kv(&mut out, "ttl", &answers.ttl);
    out.push('\n');

    // Warnings as trailing comments.
    if !probe.warnings.is_empty() {
        push_comment(&mut out, "");
        push_comment(&mut out, "Warnings from the probe:");
        for w in &probe.warnings {
            push_comment(&mut out, &format!("  - {w}"));
        }
    }

    out
}

const BASE_EXEC_PATH: &[&str] = &["/usr/bin", "/usr/local/bin", "/bin"];

fn push_comment(out: &mut String, text: &str) {
    out.push_str("# ");
    out.push_str(text);
    out.push('\n');
}

fn push_section_comment(out: &mut String, title: &str) {
    let dashes = 72 - title.len() - 5; // "# --- " + " " + dashes
    out.push_str("# --- ");
    out.push_str(title);
    out.push(' ');
    for _ in 0..dashes {
        out.push('-');
    }
    out.push('\n');
}

fn push_kv(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = \"");
    out.push_str(value);
    out.push_str("\"\n");
}
