//! Compile `bpf/*.bpf.c` against the kernel UAPI (no CO-RE) and embed the
//! objects, when the `embed-programs` feature is enabled.
//!
//! Gating this on a feature keeps a plain `cargo build` clang-free; consumers
//! that need the loadable programs at runtime (e.g. `kennel-lib-spawn`) turn the
//! feature on, which is when clang (pinned per `BUILD-ENV.md`) is required. The
//! generated `programs.rs` exposes `PROGRAM_OBJECTS: &[(&str, &[u8])]`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    // Only compile when asked; otherwise this build script is a no-op.
    if std::env::var_os("CARGO_FEATURE_EMBED_PROGRAMS").is_none() {
        return;
    }
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let bpf_dir = Path::new(&manifest).join("../../bpf");
    println!("cargo:rerun-if-changed={}", bpf_dir.display());

    // Collect bpf/*.bpf.c in a deterministic order.
    let read = std::fs::read_dir(&bpf_dir).expect("read bpf dir");
    let mut sources: Vec<PathBuf> = read
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.to_str().is_some_and(|s| s.ends_with(".bpf.c")))
        .collect();
    sources.sort();

    // The BPF object runs on the privhelper's host kernel, so it is compiled for the
    // *target* arch (`CARGO_CFG_TARGET_ARCH`), not whatever the build host happens to be:
    // both the `__TARGET_ARCH_*` token and the multiarch UAPI include path follow it. This
    // keeps native builds working on every supported arch, and cross-builds working when the
    // target's multiarch headers are installed (`<arch>-linux-gnu`; from `linux-libc-dev`).
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").expect("CARGO_CFG_TARGET_ARCH");
    let (bpf_arch, multiarch) = match target_arch.as_str() {
        "x86_64" => ("x86", "x86_64-linux-gnu"),
        "aarch64" => ("arm64", "aarch64-linux-gnu"),
        // Fail the build cleanly (no `panic!`, denied by clippy::panic) with a helpful note.
        other => {
            println!(
                "cargo:warning=kennel-lib-bpf: unsupported target arch {other:?}; \
                 add its BPF __TARGET_ARCH token and multiarch include dir"
            );
            std::process::exit(1);
        }
    };
    let target_arch_def = format!("-D__TARGET_ARCH_{bpf_arch}");
    let multiarch_inc = format!("-I/usr/include/{multiarch}");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for src in &sources {
        let name = src
            .file_name()
            .and_then(|n| n.to_str())
            .and_then(|n| n.strip_suffix(".bpf.c"))
            .expect("bpf source name")
            .to_owned();
        let obj = Path::new(&out_dir).join(format!("{name}.o"));
        // Same flags as the loader's verified test: UAPI headers, BPF target, no CO-RE.
        let status = Command::new("clang")
            .args([
                "-O2",
                "-Wall",
                "-target",
                "bpf",
                target_arch_def.as_str(),
                "-c",
            ])
            .arg("-I")
            .arg(&bpf_dir)
            .args(["-I/usr/include", multiarch_inc.as_str()])
            .arg(src)
            .arg("-o")
            .arg(&obj)
            .status()
            .expect("run clang");
        assert!(
            status.success(),
            "clang failed to compile {}",
            src.display()
        );
        entries.push((name, obj));
    }

    // Each object is embedded as an 8-byte-aligned static: `include_bytes!`
    // yields only byte-aligned data, but `object`'s zero-copy ELF parsing needs
    // the buffer aligned for its 64-bit field reads.
    let mut gen = String::from(
        "/// Compiled BPF objects, keyed by program name (generated by build.rs).\n\
         pub const PROGRAM_OBJECTS: &[(&str, &[u8])] = &[\n",
    );
    for (name, obj) in &entries {
        let path = obj.to_str().expect("object path is UTF-8");
        let len = std::fs::metadata(obj).expect("object size").len();
        writeln!(
            gen,
            "    ({name:?}, {{ #[repr(C, align(8))] struct A([u8; {len}]); \
             static D: A = A(*include_bytes!({path:?})); &D.0 }}),"
        )
        .expect("write entry");
    }
    gen.push_str("];\n");
    std::fs::write(Path::new(&out_dir).join("programs.rs"), gen).expect("write programs.rs");
}
