//! `gen-man` — Project Kennel's build-time manpage generator (not shipped).
//!
//! A thin CLI over the `gen_man` library: emits groff `man(7)` source for the
//! shipped binaries and user-touchable config files. Std-only.
//!
//! Usage:
//! - `gen-man --out DIR` — write every page to `DIR/<name>.<section>`.
//! - `gen-man --list` — print the `<name>.<section>` of every page (one per line).
//! - `gen-man NAME.SECTION` — write one page to stdout (e.g. `gen-man kennel.1`).
//!
//! The committed pages under `man/` are regenerated by this tool; a CI check runs
//! `--out` and asserts `git diff` is empty, so the pages cannot drift from the data.

use std::io::Write as _;
use std::path::Path;
use std::process::ExitCode;

use gen_man::pages::PAGES;
use gen_man::render;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("--out") => args.get(1).map_or_else(
            || fail("usage: gen-man --out DIR"),
            |dir| write_all(Path::new(dir)),
        ),
        Some("--list") => {
            for p in PAGES {
                println!("{}.{}", p.name, p.section);
            }
            ExitCode::SUCCESS
        }
        Some(one) if !one.starts_with('-') => write_one_to_stdout(one),
        _ => fail("usage: gen-man (--out DIR | --list | NAME.SECTION)"),
    }
}

fn fail(msg: &str) -> ExitCode {
    eprintln!("gen-man: {msg}");
    ExitCode::FAILURE
}

/// Write every page into `dir` as `<name>.<section>`.
fn write_all(dir: &Path) -> ExitCode {
    if let Err(e) = std::fs::create_dir_all(dir) {
        return fail(&format!("cannot create {}: {e}", dir.display()));
    }
    for p in PAGES {
        let path = dir.join(format!("{}.{}", p.name, p.section));
        if let Err(e) = std::fs::write(&path, render(p)) {
            return fail(&format!("cannot write {}: {e}", path.display()));
        }
    }
    println!("gen-man: wrote {} pages to {}", PAGES.len(), dir.display());
    ExitCode::SUCCESS
}

/// Write the single page named `name.section` to stdout.
fn write_one_to_stdout(spec: &str) -> ExitCode {
    let Some((name, section)) = spec.rsplit_once('.') else {
        return fail(&format!("not a NAME.SECTION: {spec}"));
    };
    let Some(page) = PAGES
        .iter()
        .find(|p| p.name == name && section.parse::<u8>().ok() == Some(p.section))
    else {
        return fail(&format!("no such page: {spec}"));
    };
    match std::io::stdout().write_all(render(page).as_bytes()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => fail(&format!("write: {e}")),
    }
}
