
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.memchr]]
version = "2.8.1"
criteria = "safe-to-deploy"

[[exemptions.numtoa]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.termion]]
version = "4.0.6"
criteria = "safe-to-deploy"
