//! Render the inventory as the markdown that lands between the generated markers in
//! `03-crate-decomposition.md`: the inventory table plus the totals line.

use crate::{short_name, Inventory};
use std::fmt::Write as _;

/// The marker that opens the generated region (everything to [`END`] is rewritten by the tool).
pub const BEGIN: &str =
    "<!-- BEGIN GENERATED: crate-inventory (gen-inventory; do not edit by hand) -->";
/// The marker that closes the generated region.
pub const END: &str = "<!-- END GENERATED: crate-inventory -->";

/// The markdown body (table + totals) for the generated block, without the markers themselves.
#[must_use]
pub fn body(inv: &Inventory) -> String {
    let mut s = String::new();
    s.push_str(
        "*Generated by `gen-inventory` from the workspace — do not hand-edit; \
         run `cargo run -p gen-inventory -- --json docs/architecture/crate-inventory.json \
         --doc docs/architecture/03-crate-decomposition.md`. The source of truth is \
         `crate-inventory.json`.*\n\n",
    );
    s.push_str("| Crate | SLOC | unsafe | TCB | Consumers | External deps |\n");
    s.push_str("|---|--:|:--:|:--:|---|---|\n");
    for c in &inv.crates {
        // Writing to a `String` is infallible.
        let _ = writeln!(
            s,
            "| `{}` | {} | {} | {} | {} | {} |",
            c.name,
            c.sloc,
            mark(c.uses_unsafe),
            mark(c.in_tcb),
            consumers(c),
            ext(&c.ext_deps),
        );
    }
    // First-party dependency edges (who pulls what), name-sorted; external deps are in the table.
    s.push_str("\n**Internal dependency edges (who pulls what):**\n\n");
    let mut by_name: Vec<&crate::CrateInfo> = inv.crates.iter().collect();
    by_name.sort_by(|a, b| a.name.cmp(&b.name));
    for c in by_name {
        let fp: Vec<String> = c.fp_deps.iter().map(|d| short_name(d)).collect();
        if !fp.is_empty() {
            let _ = writeln!(s, "- `{}` → {}", c.name, fp.join(", "));
        }
    }
    let _ = write!(
        s,
        "\n**Totals.** {} crates, **{} SLOC** (excluding `#[cfg(test)]`). The runtime **TCB closure** \
         (the first-party dependency graph of `kenneld` / `kennel-privhelper` / `kennel-bin-init`) is \
         {} crates, **{} SLOC**; the remaining {} crates ({} SLOC) are outside it (the operator CLI \
         and its deps, the in-kennel facades, and the out-of-TCB D-Bus mediation engine).\n",
        inv.crate_count,
        inv.total_sloc,
        inv.tcb_count,
        inv.tcb_sloc,
        inv.crate_count.saturating_sub(inv.tcb_count),
        inv.total_sloc.saturating_sub(inv.tcb_sloc),
    );
    s
}

/// A boolean cell: `**yes**` or `—`.
const fn mark(yes: bool) -> &'static str {
    if yes {
        "**yes**"
    } else {
        "—"
    }
}

/// The consumers cell: the reverse first-party edges, or a `*(… bin …)*` note for a leaf binary.
fn consumers(c: &crate::CrateInfo) -> String {
    if !c.consumers.is_empty() {
        return c.consumers.join(", ");
    }
    match c.bins.len() {
        0 => "—".to_owned(),
        1 => "*(binary)*".to_owned(),
        n => format!("*({n} bins)*"),
    }
}

/// The external-deps cell.
fn ext(deps: &[String]) -> String {
    if deps.is_empty() {
        "—".to_owned()
    } else {
        deps.join(", ")
    }
}

/// Replace the region between [`BEGIN`] and [`END`] in `doc` with a freshly rendered block. If the
/// markers are absent, the block is appended (so a first run wires them in).
#[must_use]
pub fn splice_into(doc: &str, inv: &Inventory) -> String {
    let block = format!("{BEGIN}\n\n{}\n{END}", body(inv));
    match (doc.find(BEGIN), doc.find(END)) {
        (Some(b), Some(e)) if e > b => {
            let end = e.saturating_add(END.len());
            let before = doc.get(..b).unwrap_or("");
            let after = doc.get(end..).unwrap_or("");
            format!("{before}{block}{after}")
        }
        _ => {
            let sep = if doc.ends_with('\n') { "\n" } else { "\n\n" };
            format!("{doc}{sep}{block}\n")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{CrateInfo, Inventory};

    fn sample() -> Inventory {
        Inventory {
            crates: vec![CrateInfo {
                name: "kenneld".to_owned(),
                sloc: 100,
                uses_unsafe: false,
                in_tcb: true,
                consumers: vec![],
                bins: vec!["kenneld".to_owned(), "kennel-akc".to_owned()],
                fp_deps: vec![],
                ext_deps: vec!["serde".to_owned()],
            }],
            crate_count: 1,
            total_sloc: 100,
            tcb_count: 1,
            tcb_sloc: 100,
        }
    }

    #[test]
    fn splice_replaces_between_markers() {
        let doc = format!("before\n{BEGIN}\nold\n{END}\nafter\n");
        let out = splice_into(&doc, &sample());
        assert!(out.starts_with("before\n"));
        assert!(out.trim_end().ends_with("after"));
        assert!(out.contains("`kenneld`"));
        assert!(!out.contains("old"));
        assert!(out.contains("*(2 bins)*")); // two bins, no consumers
    }

    #[test]
    fn splice_appends_when_markers_absent() {
        let out = splice_into("no markers here\n", &sample());
        assert!(out.contains(BEGIN));
        assert!(out.contains(END));
    }
}
